### ISSUE TITLE
how to set clickarea properly?

### ISSUE THREAD

**Issue by lolaswift** [stionic/com-stionic-facebookads#2]

**Comment by stionic** [comment]
hi,

Why you closed it? Am finding get header & footer height in ionic1.
You need calcular if over header & footer.
if 0 < y < headerHight => y = headerHight & h = h - (headerHight - y)
if y < 0 & y + h > headerHeight => y = headerHeight & h = h - headerHight - Math.abs(y)

Regards.

**Comment by lolaswift** [comment]
I thought I fix  the issue that's why I closed it. 
But I still haven't, just found out. Glad that you reopened the issue because I do need your help.
Your app handle it well. How do you do it? Using the above formula? What's the height of the footer and the header? I don't know how to get their height in ionic 1.x

**Comment by stionic** [comment]
Hi,

You just make sure that nothing over ads.
Don't have exactly formula because it depending your app and page.
Our app use Ionic 3 so it easy for control. I have tried finding get header height in ionic1 but not found. You also can fixed it.

Regards.

**Comment by lolaswift** [comment]
I am already working on the ionic 3 version but because it's taking longer than what I thought, I have to deal with the ionic 1.x version now unfortunately.

**Comment by lolaswift** [comment]
so it's 44px, the navbar, I just inspected the web element. Can't find anywhere the height .

**Comment by lolaswift** [comment]
are you sure about: if 0 < y < headerHight => y = headerHight & h = h - (headerHight - y)
in this case, assume the header size is 44px:
 y=44
h=h-(44-44)
So the h makes no sense. The result is there is no overlap of the header but the bottom of the card overlaps with the card below

**Comment by stionic** [comment]
ah, my mistake. Just set y after set h.

It should be:
h = h - (headerHeight - y);
y = headerHeight;

**Comment by lolaswift** [comment]
ah, thx.

btw, it doesn't work. when scrolling down the native Ad card till around half of the Ad card covered by the header, the header become clickable and some area below the Ad card starts becoming clickable too.
This is how I do it.
when the ads displays on top(right below the header bar) and before scrolling happens. I get the w, h, x, y like this:
=================================================
      var w = document.getElementById('fbanCard').clientWidth;
      var h = document.getElementById('fbanCard').clientHeight;
      var x = document.getElementById('fbanCard').offsetLeft + 80;
      var y = document.getElementById('fbanCard').offsetTop + 80;
=================================================

I have to compensate with 80 to make the exact Ad card clickable,otherwise, the click area goes above the header bar and the bottom of the card is not clickable. So far so good.

When scrolling starts, I do it like this:

================================================
          var w = document.getElementById('fbanCard').clientWidth;
          var h = document.getElementById('fbanCard').clientHeight;
          var x = document.getElementById('fbanCard').offsetLeft + 80 -  $ionicScrollDelegate.$getByHandle('mainScroll').getScrollPosition().left;
          var y = document.getElementById('fbanCard').offsetTop + 80 - $ionicScrollDelegate.$getByHandle('mainScroll').getScrollPosition().top;

    if (0 < y && y < 44) {
        h = h - (44 - y);
        y = 44;
      }
=================================================
when scroll down to around half of the Ad card, the header become clickable and the clickable area extends to the area below the Ad card.


The problem is here:
      console.log("offsettop", document.getElementById('fbanCard').offsetTop)
always output '0'.  This is wrong, correct? offsetTop means the top position of the element, in our case, the AD card, correct? When we scroll down, shouldn't the offsetTop change as well?

**Comment by lolaswift** [comment]
sorry about the format

**Comment by stionic** [comment]
hi,

it is our logic in Ionic 3, sorry for delay, i am out of office in sunday.
I don't know what it should be in Ionic 1, Maybe it will help
dimensions.contentTop == headerHeight
dimensions.contentHeight == contentHeight (NOT content scroll height)

```
		let native = this.content.getScrollElement().querySelector('#facebook-native');
		var dimensions = this.content.getContentDimensions();
		var x = native['offsetLeft'] - dimensions.scrollLeft;
		var y = native['offsetTop'] - dimensions.scrollTop;
		var w = native['clientWidth'];
		var h = native['clientHeight'];
		// if ads over top content && part in content
		if (y < 0 && (y + h) > -dimensions.contentTop) {
			h += y;
			y = 0;
		}
		// if ads over bottom content
		if (y + h > dimensions.contentHeight) h = dimensions.contentHeight - y;
		y += dimensions.contentTop;
```

Regards.

**Comment by lolaswift** [comment]
Many thanks for your help even on Sunday. I guess it's pretty late already in your country.
To make it work is with ionic 1.x is not so straight forward for inexperience developer like me. I will give it one more try. If it doesn't work, I will leave it for now and do it in my ionic 3 version which I have finished 70%

**Comment by stionic** [comment]
Hi,

It should work perfect even Ionic 1. Just convert dimensions.contentTop == headerHeight, and find the way get content height in Ionic1.
ContentHeight = WindowHeight - headerHeight - footerHeight

Regards.

**Comment by lolaswift** [comment]
Great! Let me try.

**Comment by lolaswift** [comment]
Got it work! I almost gave up if it wasn't because of you. :-). Thank you so much!!    
      var headerHeight = 45;
      var footerHeight = 45;
      var w = document.getElementById('myCard').clientWidth;
      var h = document.getElementById('myCard').clientHeight;
      var x = document.getElementById('myCard').offsetLeft - left;
      var y = document.getElementById('myCard').offsetTop - (top - headerHeight);

      if (y > 0 && y < headerHeight) {
        h = h - y - headerHeight;
        y = headerHeight
      }

      if (y < 0) {
        h = h + y - headerHeight
        y = headerHeight
      }

      var contentHeight = $window.innerHeight - headerHeight - footerHeight;

      if (y + h > contentHeight) {
        h = contentHeight - y;
        y += headerHeight;
      }

**Comment by stionic** [comment]
@lolaswift 
Nice work ;)
